[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#6272a4"
blue = "#8aadf4"
cyan = "#7dc4e4"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#cad3f5"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#21222c"
blue = "#8aadf4"
cyan = "#7dc4e4"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"

[colors.primary]
background = "#282a36"
bright_foreground = "#cad3f5"
foreground = "#cad3f5"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fafb"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
#shape = "Block"

[debug]
log_level = "OFF"
persistent_logging = false
render_timer = false

[font]
#size = 16.0
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 1
#opacity = 0.80
#opacity = 0.40
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

[terminal]
