$wallpaper = /home/sajal/.config/swww/default.png
$background = 101417
$foreground = e0e3e8
$color0 = 363a3e
$color1 = 5baff4
$color2 = 67b5f5
$color3 = 73baf6
$color4 = 7fc0f6
$color5 = 8bc6f7
$color6 = 97ccf8
$color7 = c1c7ce
$color8 = 41474d
$color9 = 8bc7ff
$color10 = 98cdff
$color11 = a5d4ff
$color12 = b2daff
$color13 = bee0ff
$color14 = cbe6ff
$color15 = e0e3e8

$primary = 97ccf8
$secondary = b8c8d9
$tertiary = d0bfe8
$surface = 101417
$surface_bright = 363a3e
$error = ff5945

exec = ln -sf $wallpaper ~/.current.wall
# exec = pywalfox update
# exec = fabric-cli exec ax-bar 'app.set_stylesheet_from_file(get_relative_path("main.css"))'
