#!/bin/sh


name=$(bemenu -p 'Enter File name:' -H 35 --hp 10 --fn 'JetBrains Mono Nerd [16]' < /dev/null | sed 's/ /%20/g')

if [[ $name == *"."* ]]; then
	ext=$( echo $name | cut -d '.' -f 2)
	if [[ $ext == "c" ]]; then
		clang-format --style=file -i ~/stuff/c/$name
		alacritty --hold -e sh -c "gcc ~/stuff/c/$name -o /tmp/running.out -Wall; /tmp/running.out"
		#alacritty --hold -e sh -c "/tmp/running.out"
		#gnome-terminal -- sh -c "gcc ~/stuff/c/$name -o /tmp/running.out -Wall; /tmp/running.out"
	fi
else
	alacritty --title nvim -e sh -c "nvim ~/stuff/$name/temp.$name"
fi

